include $(FUZIX_ROOT)/Target/rules.$(USERCPU)

CSRCS = beep.c blockio.c display.c doscall.c editcor.c exec.c find.c
CSRCS += flexcall.c gemcall.c globals.c insert.c main.c misc.c modify.c
CSRCS += move.c rmxcall.c ucsd.c undo.c unixcall.c wildargs.c
HDRS  = extern.h grep.h levee.h proto.h

OBJSA = $(addprefix ansi-,$(CSRCS:.c=.o))
OBJSV = $(addprefix vt52-,$(CSRCS:.c=.o))

all: levee-ansi levee-vt52

levee-ansi: $(OBJSA)
	$(LINKER) -o levee-ansi $(CRT0) $(OBJSA) $(LINKER_OPT) $(LINKER_TAIL)

levee-vt52: $(OBJSV)
	$(LINKER) -o levee-vt52 $(CRT0) $(OBJSV) $(LINKER_OPT) $(LINKER_TAIL)

ansi-%.o: %.c $(HDRS)
	$(CC) $(CFLAGS) $(COPT) -c -DVT52=0 -DANSI=1 -o $@ $<

vt52-%.o: %.c $(HDRS)
	$(CC) $(CFLAGS) $(COPT) -c -DVT52=1 -DANSI=0 -o $@ $<

clean:
	rm -rf $(OBJSA) $(OBJSV) *.lst *.sym *.map *.noi *.lk *.ihx *.tmp *~ *.o *.rel *.asm
	rm -f levee levee-vt52 levee-ansi *.bin levee-termcap
